### ISSUE TITLE
Preferred Location add should allow custom typed cities 

### ISSUE THREAD

**Issue by samprits5** [findcoderapp/bugsAndFeatures#12]
In the preferred-location-add section, the user should be able to add custom Typed Cities as well. Currently, it is not allowing us to enter anything else other than the default ones.
![03 10 2021_12 52 50_REC](https://user-images.githubusercontent.com/39467315/135744380-5deb547e-37e8-418e-9c2d-ff648da66132.png)

**Comment by hiteshchoudhary** [comment]
Entering custom names leads to confusion in search. Let us know if we are missing any city.
