### ISSUE TITLE
Add Skills should allow custom typed skills

### ISSUE THREAD

**Issue by samprits5** [findcoderapp/bugsAndFeatures#13]
Users should be able to type the custom skills other than the default ones that are already set. Currently, the application doesn't support that, but it is needed.
![03 10 2021_12 53 10_REC](https://user-images.githubusercontent.com/39467315/135744428-d97d57c2-444e-44e4-ad54-f3a53b0a9b73.png)

**Comment by hiteshchoudhary** [comment]
Custom typed skills create trouble in searching, for example: React, react, reactjs, react-js react js etc.
If you need more tags, just let us know what we are missing
