### ISSUE TITLE
Chat section bug

### ISSUE THREAD

**Issue by samprits5** [findcoderapp/bugsAndFeatures#14]
When I click on the chat section, it throws an error.
![chat](https://user-images.githubusercontent.com/39467315/135744529-de704b72-3ccb-4e71-be4b-fa19f1da11ff.png)

**Comment by anirudhuuu** [comment]
A related issue same on chat, for logged-in user when visited their own profile got an option to perform 'Direct Message'

![image](https://user-images.githubusercontent.com/25549847/135751263-21df52f2-72b2-4653-95f4-1ee74f66d52b.png)
