### ISSUE TITLE
Allow slashes in adding about section

### ISSUE THREAD

**Issue by samprits5** [findcoderapp/bugsAndFeatures#15]
Please allow the slashes and other important special characters while adding about-section. It is needed, as some tech terms need some special characters like CI/CD, MVC/MVT, etc.
![slash](https://user-images.githubusercontent.com/39467315/135746109-8fb6e896-c409-44ef-9ad6-3c79edf5d8d2.png)

**Comment by hiteshchoudhary** [comment]
As of now filter special characters is not on priority. It will introduce XSS and similar attacks. we need to write custom validator for this.
