### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by wajeshubham** [findcoderapp/bugsAndFeatures#3]
- [ ] Username field error without clicking submit or getting out of focus 
[REFERENCE_IMAGE](https://user-images.githubusercontent.com/62889697/135721190-6440afa1-b84e-4591-8432-d51206eedc01.png)
### Possible reason:
- Server responding with 404 at /check/username api call may be its checking with empty string
------------------------------------------------------------------------------------------------------------------------------------------
- [ ] Cant access **Additional Information** tab at **https://findcoder.io/profile/setup/**
[ERROR IN CONSOLE](https://user-images.githubusercontent.com/62889697/135721236-53a2aeec-a681-4e92-8491-261122b71337.png)
### Possible reason:
- i skipped project form
------------------------------------------------------------------------------------------------------------------------------------------

- [x] Can't access **/chat** route
- [x] Can't access **/profile** route [RESPONSE ERROR IMAGE](https://user-images.githubusercontent.com/62889697/135722052-e54d6db3-ef2a-45f0-896e-5aa5a45aa62f.png)
- [x] can't access **/collections** route and as soon as i hit this route it redirects me to login page
- [x] reset state of add skill dropdown input after i select the skill from dropdown 
- [x] Getting 400 while adding Experience [ERROR RESPONSE](https://user-images.githubusercontent.com/62889697/135745404-6e748d12-b2bc-4f32-a7fc-066ad1732ec7.png)
- [x] After highlighting a project my other 3 projects that i added previously are gone [PROJECTS IMG](https://user-images.githubusercontent.com/62889697/135745845-2cb2c601-15b0-487f-8d56-84babdd08a22.png) 👈 there are suppose to be 4 projects but there is only 1
- [x] Like functionality on project not working. Its redirecting me to login page and again redirects me to **/search/talent**

**Comment by hiteshchoudhary** [comment]
@ProFullStackDev Need to add a "more" button if projects are more than 3. This button will redirect to all projects by this user.
