### ISSUE TITLE
Edit dialog accidently closed: UX improvement

### ISSUE THREAD

**Issue by iamkishansharma** [findcoderapp/bugsAndFeatures#8]
The **edit dialog** is getting canceled after clicking outside of the dialog box.  And the filled data is getting vanished.
I mean there is a  cross " X " on top of the dialog to dismiss the dialog.

**Comment by hiteshchoudhary** [comment]
In the current flow, popups are supposed to do that. If you don't save, we don't save anything. This is to avoid accidental updates.

**Comment by iamkishansharma** [comment]
But there is the cancel button on the top-right of every dialog to close it.
